Repository unb-mds/Sonorus-2025.1, pull requests merged in 2025-07, with the labels that each got.

#76 Melhorando tratamento de áudio.
  requirements.txt
  src/backend/api/endpoints_voz.py
  src/backend/services/voz_service.py
  src/frontend/src/Components/Login/Login.css
  src/frontend/src/Components/Login/Login.jsx
  src/frontend/src/Components/TelaErro/ErroCadastro.jsx
  src/frontend/src/Components/TelaErro/ErroLeitura.jsx
  src/frontend/src/Components/TelaFuncionou/SucessoCadastro.jsx
  src/frontend/src/Components/TelaFuncionou/VozCadastrada.jsx
Labels: bug, enhancement

#77 Melhorias na UI
  src/frontend/package.json
  src/frontend/public/sonorus_ed.png
  src/frontend/public/sororus_menor.png
  src/frontend/src/Components/Login/Login.css
  src/frontend/src/Components/Login/Login.jsx
  src/frontend/src/Components/Registro/Register.css
  src/frontend/src/Components/Registro/Register.jsx
  src/frontend/src/Components/TelaErro/ErroCadastro.css
  src/frontend/src/Components/TelaErro/ErroCadastro.jsx
  src/frontend/src/Components/TelaErro/ErroLeitura.css
  src/frontend/src/Components/TelaErro/ErroLeitura.jsx
  src/frontend/src/Components/TelaFuncionou/SucessoCadastro.css
  src/frontend/src/Components/TelaFuncionou/SucessoCadastro.jsx
  src/frontend/src/Components/TelaFuncionou/VozCadastrada.css
  src/frontend/src/Components/TelaFuncionou/VozCadastrada.jsx
  src/frontend/src/Components/TelaLeituraVoz/VozCadastro.css
  src/frontend/src/Components/TelaLeituraVoz/VozCadastro.jsx
  src/frontend/src/Components/TelaLeituraVoz/VozLogin.css
  src/frontend/src/Components/TelaLeituraVoz/VozLogin.jsx
Labels: enhancement

#74 Aumenta cobertura de testes
  .gitignore
  audios/lemes.wav
  audios/vo_lemes.wav
  audios/voz_usuario.wav
  docs/atas/Sprint 0/2025_04_07.md
  docs/atas/Sprint 0/2025_04_12.md
  docs/atas/Sprint 1/2025_04_22.md
  docs/atas/Sprint 1/2025_04_24.md
  docs/atas/Sprint 2/2025_04_26.md
  docs/atas/Sprint 2/2025_05_10.md
  docs/atas/Sprint 3/2025_05_10.2.md
  docs/atas/Sprint 3/2025_05_17.md
  docs/atas/Sprint 4/2025_05_24.md
  docs/atas/Sprint 4/2025_05_28.md
  docs/atas/Sprint 5/2025_05_31.md
  docs/atas/Sprint 5/2025_06_19.md
  docs/atas/Sprint 6/2025_06_22.md
  docs/atas/Sprint 6/2025_07_06.md
  docs/database/import.md
  docs/estudos/Machine Learning.md
  requirements.txt
  src/backend/database/database.py
  src/backend/database/models/backup.py
  src/backend/database/scripts/backup_automatico/backup.py
  src/backend/services/autenticacao_voz.py
  src/backend/utils/excluirUsuariosPSQL.py
  src/backend/utils/gravar_wav.py
  tests/backend/api/test_autenticacao.py
  tests/backend/database/test_db_connection.py
  tests/backend/database/test_redis_conex.py
  tests/backend/models/test_modelo_ecapa.py
  tests/backend/models/test_modelos.py
  tests/backend/models/test_sqlalchemy.py
  tests/backend/services/test_autenticacao_voz.py
  tests/backend/services/test_voz_service.py
  tests/backend/test_main.py
  tests/backend/utils/test_utilities.py
Labels: enhancement

#86 Adiciona função para remover usuário sem voz em caso de erro no registro
  src/backend/api/endpoints_voz.py
  src/backend/services/voz_service.py
Labels: bug

#85 adiciona função para remover usuário em caso de erro no registro de voz
  src/backend/api/endpoints_voz.py
  src/backend/services/voz_service.py
Labels: bug

#87 Atualiza Dockerfile e docker-compose.yml para incluir suporte ao Redi…
  Dockerfile
  README.md
  docker-compose.yml
  src/frontend/Dockerfile
Labels: bug

#88 adição de documentação de testes de integração do projeto
  tests/integracao/integracao_backend_frontend.md
Labels: documentation
